import = [
	"~/.config/alacritty/fonts.toml"
	"~/.config/alacritty/dark.toml"
]

[env]
TERM = "alacritty"

[shell]
args = ["--login"]
program = "/bin/zsh"

[window]
decorations = "none"
dynamic_padding = true
dynamic_title = true
opacity = 1.0
startup_mode = "Maximized"

[window.padding]
x = 6
y = 12


